**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [9]:
def my_arange(number):
    arange = np.full(int(number),int(number)) - np.arange(1, int(number)+1)
    return(arange)

In [10]:
my_arange(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

***Задание 2***

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
def my_matrix(number):
    matrix = np.diag(my_arange(int(number)))
    return(matrix)

In [21]:
matrix = my_matrix(11)
matrix

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [22]:
np.trace(matrix)


55

***Задание 3***

Решите систему уравнений: 4x + 2y + z = 4 x + 3y = 12 5y + 4z = -3

In [23]:
from numpy import linalg

In [24]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [25]:
b = np.array( [ 4, 12, -3 ] )

In [26]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [27]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Задача 4 домашнего задания**

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [28]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [29]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [31]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [39]:
my_list = []
for i in users_stats:
    my_list.append(cosine(i, next_user_stats))

print('Cамый похожий поситетель под номером', my_list.index(max(my_list)) + 1)

Cамый похожий поситетель под номером 8
